services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-app:latest
    ports:
      - "80:8000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
