services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-app:latest
    ports:
      - "80:8000"
    restart: unless-stopped
    environment:
      - DD_AGENT_HOST=datadog    # [APM]トレース情報の送信先を指定
      - DD_ENV=demo              # [APM]サービスの環境を指定
      - DD_SERVICE=web           # [APM]サービスの名前を指定
      - DD_VERSION=ver1.0        # [APM]サービスのバージョンを指定
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
  datadog:
    container_name: dd-agent
    image: datadog/agent:latest
    links:
      - web
    environment:
      - DD_API_KEY=<Your_Datadog_API_Key>                         # (必須)Datadogへ送信用のAPI keyを設定
      - DD_SITE=ap1.datadoghq.com                                 # (必須)Datadog Endpointの設定
      - DD_AGENT_HOST=dd-agent                                    # (必須)DatadogのAgent Hostを自分自身に設定
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true                       # (任意)カスタムメトリクス収集の有効化
      - DD_APM_ENABLED=true                                       # (任意)[APM]APM機能の有効化
      - DD_APM_NON_LOCAL_TRAFFIC=true                             # (任意)[APM]APM機能の有効化
      - DD_LOGS_ENABLED=true                                      # (任意)[Logs]ログ収集の有効化
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true                 # (任意)[Logs]コンテナログを収集
      - DD_CONTAINER_EXCLUDE_LOGS=name:dd-agent                   # (任意)[Logs]収集ログからdd-agentのログを除外
      - DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED=true         # (任意)[Live Processes]Process収集の有効化
      - DD_SYSTEM_PROBE_NETWORK_ENABLED=true                      # (任意)[Cloud Network]Cloud Networkの有効化
      - DD_PROCESS_AGENT_ENABLED=true                             # (任意)[Cloud Network]Cloud Networkの有効化
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock                 # (必須)Agentのベーシック実行に必要なマウント
      - /proc/:/host/proc/:ro                                     # (必須)Agentのベーシック実行に必要なマウント
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro                     # (必須)Agentのベーシック実行に必要なマウント
      - /var/lib/docker/containers:/var/lib/docker/containers:ro  # (任意)[Logs]Agentによるログ収集に必要なマウント
      - /etc/passwd:/etc/passwd:ro                                # (任意)[Live Processes]Process収集の有効化
